// Mock data for the prototype. Mirrors the shape implied by D33–D40
// closely enough to feel real without committing to backend wiring.
// Replace with API calls when wiring lands.

export const jumper = {
  name: 'Alex',
  exitWeight: 200,
  weightUnit: 'lb',
  weightUpdated: '3 months ago',
  weightStale: false,
  defaultJurisdiction: 'USPA',
};

export const rigs = [
  {
    id: 'rig-sport',
    name: 'Sport rig',
    jurisdiction: 'both',
    uspaDays: 15,
    cspaDays: 105,
    wingloading: 1.18,
    status: 'yellow',
    main: {
      id: 'main-sabre2',
      brand: 'Performance Designs',
      model: 'Sabre2',
      size: 150,
      serial: 'SBR-9921',
      jumps: 198,
      dom: '03/2024',
      lineset: { type: 'V750', remaining: 73, jumps: 198, installed: '01/2024' },
      status: 'green',
      notes: [
        { date: '2026-04-12', author: 'Alex', content: 'Slider keepers replaced after 180 jumps.' },
        { date: '2024-05-02', author: 'Rigger Dan', content: 'New install, V750 Vectran lineset.' },
      ],
    },
    reserve: {
      id: 'reserve-optimum143',
      brand: 'Performance Designs',
      model: 'PD Optimum',
      size: 143,
      serial: 'OPT-4410',
      dom: '08/2023',
      repacks: 12,
      repackLimit: 40,
      rides: 0,
      rideLimit: 25,
      status: 'yellow',
      notes: [
        { date: '2026-02-12', author: 'Rigger Dan', content: 'Standard I&R, no findings.' },
        { date: '2025-08-08', author: 'Rigger Dan', content: 'Six-month inspection, returned to service.' },
      ],
    },
    aad: {
      id: 'aad-vigil2',
      brand: 'Advanced Aerospace Designs',
      model: 'Vigil 2+',
      mode: 'Pro',
      dom: '06/2022',
      jumps: 198,
      fires: 0,
      nextAction: 'Battery replacement 06/2032',
      daysToAction: 2227,
      status: 'green',
      modeMatch: true,
      notes: [],
    },
    container: {
      id: 'container-vector348',
      brand: 'UPT',
      model: 'Vector V348',
      serial: '12345',
      dom: '2019',
      jumps: 198,
      status: 'green',
      notes: [
        { date: '2025-11-30', author: 'Rigger Dan', content: 'Cutaway cables cleaned & lubed.' },
      ],
    },
    actions: [
      { date: 'May 12', text: 'USPA repack due', days: 15, level: 'warning' },
      { date: 'Aug 10', text: 'CSPA repack due', days: 105, level: 'info' },
      { date: 'Jun 01, 2028', text: 'Vigil 2+ battery replacement', days: 2227, level: 'info' },
    ],
  },
  {
    id: 'rig-bigway',
    name: 'Big way rig',
    jurisdiction: 'USPA',
    uspaDays: 87,
    cspaDays: null,
    wingloading: 1.04,
    status: 'green',
    main: {
      id: 'main-spectre170',
      brand: 'Performance Designs',
      model: 'PD Spectre',
      size: 170,
      serial: 'SPC-1180',
      jumps: 42,
      dom: '06/2022',
      lineset: { type: 'V550', remaining: 88, jumps: 42, installed: '06/2022' },
      status: 'green',
      notes: [],
    },
    reserve: {
      id: 'reserve-optimum126',
      brand: 'Performance Designs',
      model: 'PD Optimum',
      size: 126,
      serial: 'OPT-3318',
      dom: '02/2018',
      repacks: 18,
      repackLimit: 40,
      rides: 1,
      rideLimit: 25,
      status: 'green',
      notes: [
        { date: '2024-07-19', author: 'Rigger Dan', content: 'Post-ride inspection, returned to service.' },
        { date: '2024-07-18', author: 'Alex', content: 'Reserve ride after main bag-lock.' },
      ],
    },
    aad: {
      id: 'aad-cuatro',
      brand: 'Advanced Aerospace Designs',
      model: 'Vigil Cuatro',
      mode: 'Pro',
      dom: '06/2023',
      jumps: 42,
      fires: 0,
      nextAction: 'Battery replacement 06/2033',
      daysToAction: 2592,
      status: 'green',
      modeMatch: true,
      notes: [],
    },
    container: {
      id: 'container-mirage',
      brand: 'Mirage',
      model: 'G4',
      serial: 'MG4-7712',
      dom: '2022',
      jumps: 42,
      status: 'green',
      notes: [],
    },
    actions: [
      { date: 'Jul 23', text: 'USPA repack due', days: 87, level: 'info' },
    ],
  },
  {
    id: 'rig-wingsuit',
    name: 'Wingsuit rig',
    jurisdiction: 'USPA',
    uspaDays: 142,
    cspaDays: null,
    wingloading: 1.18,
    status: 'green',
    main: {
      id: 'main-sabre2-ws',
      brand: 'Performance Designs',
      model: 'Sabre2',
      size: 150,
      serial: 'SBR-7720',
      jumps: 17,
      dom: '08/2024',
      lineset: { type: 'V750', remaining: 96, jumps: 17, installed: '08/2024' },
      status: 'green',
      notes: [],
    },
    reserve: {
      id: 'reserve-smart175',
      brand: 'Aerodyne',
      model: 'Smart',
      size: 175,
      serial: 'SMR-1180',
      dom: '06/2021',
      repacks: 6,
      repackLimit: 40,
      rides: 0,
      rideLimit: 25,
      status: 'green',
      notes: [],
    },
    aad: {
      id: 'aad-cypres2',
      brand: 'Airtec',
      model: 'Cypres 2',
      mode: 'Expert',
      dom: '03/2020',
      jumps: 17,
      fires: 0,
      nextAction: 'Service window opens 03/2028',
      daysToAction: 689,
      status: 'green',
      modeMatch: true,
      notes: [],
    },
    container: {
      id: 'container-wings',
      brand: 'Wings',
      model: 'W-22',
      serial: 'WG22-440',
      dom: '2021',
      jumps: 17,
      status: 'green',
      notes: [],
    },
    actions: [
      { date: 'Sep 16', text: 'USPA repack due', days: 142, level: 'info' },
    ],
  },
];

// Components in inventory but unassigned to any rig.
export const unassignedComponents = [
  {
    id: 'main-safire3',
    type: 'main',
    brand: 'Icarus',
    model: 'Safire 3',
    size: 169,
    serial: 'ICR-4421',
    dom: '11/2023',
    jumps: 0,
    status: 'green',
  },
  {
    id: 'reserve-optimum113',
    type: 'reserve',
    brand: 'Performance Designs',
    model: 'PD Optimum',
    size: 113,
    serial: 'OPT-9921',
    dom: '04/2024',
    repacks: 0,
    repackLimit: 40,
    rides: 0,
    rideLimit: 25,
    status: 'green',
  },
];

// Retired components that stay in the index for history.
export const retiredComponents = [
  {
    id: 'aad-cypres2-retired',
    type: 'aad',
    brand: 'Airtec',
    model: 'Cypres 2',
    serial: 'CYP-110901',
    dom: '2014',
    status: 'red',
    retired: true,
  },
];

export const dropzones = [
  {
    id: 'dz-algarve',
    name: 'Skydive Algarve',
    location: 'Alvor, Portugal',
    coords: '37.13°N, 8.59°W',
    aircraft: ['Cessna 208', 'Pilatus PC-6'],
    jumps: 167,
    lastJumped: 'Apr 20',
    home: true,
  },
  {
    id: 'dz-empuriabrava',
    name: 'Skydive Empuriabrava',
    location: 'Empuriabrava, Spain',
    coords: '42.25°N, 3.12°E',
    aircraft: ['Twin Otter', 'Pilatus PC-6'],
    jumps: 52,
    lastJumped: 'Apr 11',
    home: false,
  },
  {
    id: 'dz-dubai',
    name: 'Skydive Dubai — Desert',
    location: 'Margham, UAE',
    coords: '25.04°N, 55.62°E',
    aircraft: ['Twin Otter'],
    jumps: 18,
    lastJumped: 'Mar 27',
    home: false,
  },
  {
    id: 'dz-spaceland',
    name: 'Skydive Spaceland',
    location: 'Rosharon, Texas, USA',
    coords: '29.30°N, 95.45°W',
    aircraft: ['Caravan'],
    jumps: 7,
    lastJumped: 'Aug 2024',
    home: false,
  },
  {
    id: 'dz-hinton',
    name: 'Hinton Skydiving',
    location: 'Northamptonshire, UK',
    coords: '52.16°N, 1.12°W',
    aircraft: ['Cessna 208'],
    jumps: 3,
    lastJumped: 'Jun 2023',
    home: false,
  },
];

export const jumps = [
  { n: 247, title: 'Opening at night over the coast', date: 'Apr 20', year: '2026', dz: 'Skydive Algarve', aircraft: 'Cessna 208', canopy: 'Sabre2 150', discipline: 'Freefly', exit: 4200, ff: 58, attachments: 3 },
  { n: 246, title: '2-way sit-fly', date: 'Apr 19', year: '2026', dz: 'Skydive Algarve', aircraft: 'Cessna 208', canopy: 'Sabre2 150', discipline: 'Freefly', exit: 4000, ff: 55, attachments: 0 },
  { n: 245, title: 'Hop-n-pop, 4k', date: 'Apr 18', year: '2026', dz: 'Skydive Algarve', aircraft: 'Cessna 208', canopy: 'Spectre 170', discipline: 'Canopy', exit: 1200, ff: 5, attachments: 0 },
  { n: 244, title: 'Big way attempt — 12 way', date: 'Apr 11', year: '2026', dz: 'Skydive Empuriabrava', aircraft: 'Twin Otter', canopy: 'Sabre2 150', discipline: 'Belly', exit: 4500, ff: 62, attachments: 2 },
  { n: 243, title: 'Belly-to-back transitions', date: 'Apr 10', year: '2026', dz: 'Skydive Empuriabrava', aircraft: 'Twin Otter', canopy: 'Sabre2 150', discipline: 'Freefly', exit: 4200, ff: 60, attachments: 0 },
  { n: 242, title: 'Night jump — full moon', date: 'Apr 03', year: '2026', dz: 'Skydive Algarve', aircraft: 'Pilatus PC-6', canopy: 'Spectre 170', discipline: 'Belly', exit: 3500, ff: 48, attachments: 4 },
  { n: 241, title: 'AFF Cat E graduation', date: 'Mar 27', year: '2026', dz: 'Skydive Dubai — Desert', aircraft: 'Twin Otter', canopy: 'Navigator 260', discipline: 'Belly', exit: 4000, ff: 50, attachments: 1 },
  { n: 240, title: 'Wingsuit intro — first flocking', date: 'Mar 26', year: '2026', dz: 'Skydive Empuriabrava', aircraft: 'Pilatus PC-6', canopy: 'Sabre2 150', discipline: 'Wingsuit', exit: 4500, ff: 75, attachments: 2 },
  { n: 239, title: 'Camera flyer coaching jump', date: 'Mar 20', year: '2026', dz: 'Skydive Algarve', aircraft: 'Cessna 208', canopy: 'Sabre2 150', discipline: 'Belly', exit: 4200, ff: 60, attachments: 3 },
  { n: 238, title: 'Head-down 3-way', date: 'Mar 19', year: '2026', dz: 'Skydive Algarve', aircraft: 'Cessna 208', canopy: 'Sabre2 150', discipline: 'Freefly', exit: 4200, ff: 57, attachments: 0 },
];

export const careerStats = {
  total: 247,
  freefall: '4h 12m',
  thisYear: 32,
  last90: 28,
  currency: 'active',
  daysSinceLastJump: 7,
  yearByMonth: [3, 5, 9, 15, 0, 0, 0, 0, 0, 0, 0, 0],
  byDiscipline: [
    ['Freefly', 120],
    ['Belly', 82],
    ['Canopy', 28],
    ['Wingsuit', 17],
  ],
  byRig: [
    ['Sport rig', 198],
    ['Big way rig', 42],
    ['Wingsuit rig', 17],
  ],
  byCanopy: [
    ['PD Sabre2 150', 198],
    ['PD Spectre 170', 42],
    ['Navigator 260', 7],
  ],
};

export const aircraftLabel = (s) => s; // placeholder for future units/locale formatting
